spring:
  datasource:
    url: jdbc:mysql://mysql.tulasi1211-dev.svc.cluster.local:3306/sampledb
    username: user6NS
    password: 5Q3iY5BcXBrqwEC8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
  database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
